// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type RedirectRequest struct {
	ShortURL string `path:"shortUrl"`
}

type RedirectResponse struct {
}

type ShortenRequest struct {
	LongURL string `json:"longUrl"`
}

type ShortenResponse struct {
	ShortURL string `json:"shortUrl"`
}
