# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

dotenv: [".env"]

vars:
  CONTAINER_ENGINE:
    sh: |
      if command -v docker > /dev/null 2>&1; then
        echo "docker"
      elif command -v podman > /dev/null 2>&1; then
        echo "podman"
      else
        exit 1 # No supported container engine found
      fi
  MYSQL_COMMAND: >-
    {{.CONTAINER_ENGINE}} exec -i shorturl-mysql mysql -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}
  INTERACTIVE_MYSQL_COMMAND: >-
    {{.CONTAINER_ENGINE}} exec -it shorturl-mysql mysql -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}

tasks:
  run:
    desc: Run the short URL server.
    deps:
      - up
    cmds:
      - go run ./cmd/server
    silent: true

  generate:
    desc: Generate code using goctl
    cmds:
      - goctl api go -api shorturl.api -dir .
      - mkdir -p cmd/server
      - cp shorturl.go cmd/server/main.go
      - rm shorturl.go
      - mkdir -p internal/model
      - goctl model mysql ddl -s "sql/*.sql" --dir "internal/model"
    silent: true

  up:
    desc: Pull up containers
    deps:
      - podman-machine-start
    cmds:
      - "{{.CONTAINER_ENGINE}} compose up -d"
    silent: true

  down:
    desc: Shut down containers
    cmds:
      - "{{.CONTAINER_ENGINE}} compose down 2>/dev/null"
    silent: true

  clean:
    desc: Shut down containers and remove all data
    prompt: "DANGEROUS: Do you really want to remove all data?"
    cmds:
      - "{{.CONTAINER_ENGINE}} compose down -v 2>/dev/null"
    silent: true

  database:
    desc: Connect to database CLI
    deps:
      - up
    cmds:
      - "{{.INTERACTIVE_MYSQL_COMMAND}}"
    interactive: true
    silent: true

  migrate:
    desc: Migrate database
    deps:
      - up
    cmds:
      - task: sleep:20
      - |
        for sql in sql/*.sql; do
          {{.MYSQL_COMMAND}} < $sql
        done
    silent: true

  podman-machine-start:
    desc: Start podman machine
    internal: true
    if: '{{eq .CONTAINER_ENGINE "podman"}}'
    cmd: |
      machinestate="$(podman machine info)"
      machinestate=${machinestate##*machinestate:}
      machinestate=${machinestate%%numberofmachines*}
      case "$machinestate" in
        *Running*)
          exit 0 # Already running
          ;;
        *)
          podman machine start
          ;;
      esac
    silent: true

  sleep:*:
    desc: Sleep N seconds
    cmds:
      - task: sleep-powershell:{{index .MATCH 0}}
      - task: sleep-posix:{{index .MATCH 0}}

  sleep-powershell:*:
    desc: Sleep N seconds in PowerShell
    if: '{{eq OS "windows"}}'
    internal: true
    cmds:
      - pwsh -c "sleep {{index .MATCH 0}}"
    silent: true

  sleep-posix:*:
    desc: Sleep N seconds in POSIX Shell
    if: '{{ne OS "windows"}}'
    internal: true
    cmds:
      - sleep {{index .MATCH 0}}
    silent: true
