// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mapFieldNames          = builder.RawFieldNames(&Map{})
	mapRows                = strings.Join(mapFieldNames, ",")
	mapRowsExpectAutoSet   = strings.Join(stringx.Remove(mapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mapRowsWithPlaceHolder = strings.Join(stringx.Remove(mapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	mapModel interface {
		Insert(ctx context.Context, data *Map) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Map, error)
		FindOneByMd5(ctx context.Context, md5 sql.NullString) (*Map, error)
		FindOneBySurl(ctx context.Context, surl sql.NullString) (*Map, error)
		Update(ctx context.Context, data *Map) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMapModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Map struct {
		Id        uint64         `db:"id"`
		CreatedAt time.Time      `db:"created_at"`
		CreatedBy string         `db:"created_by"`
		IsDel     uint64         `db:"is_del"`
		Lurl      sql.NullString `db:"lurl"`
		Md5       sql.NullString `db:"md5"`
		Surl      sql.NullString `db:"surl"`
	}
)

func newMapModel(conn sqlx.SqlConn) *defaultMapModel {
	return &defaultMapModel{
		conn:  conn,
		table: "`map`",
	}
}

func (m *defaultMapModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMapModel) FindOne(ctx context.Context, id uint64) (*Map, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mapRows, m.table)
	var resp Map
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMapModel) FindOneByMd5(ctx context.Context, md5 sql.NullString) (*Map, error) {
	var resp Map
	query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", mapRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, md5)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMapModel) FindOneBySurl(ctx context.Context, surl sql.NullString) (*Map, error) {
	var resp Map
	query := fmt.Sprintf("select %s from %s where `surl` = ? limit 1", mapRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, surl)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMapModel) Insert(ctx context.Context, data *Map) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, mapRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CreatedBy, data.IsDel, data.Lurl, data.Md5, data.Surl)
	return ret, err
}

func (m *defaultMapModel) Update(ctx context.Context, newData *Map) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mapRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CreatedBy, newData.IsDel, newData.Lurl, newData.Md5, newData.Surl, newData.Id)
	return err
}

func (m *defaultMapModel) tableName() string {
	return m.table
}
